name: Update GitHub Activity

on:
  schedule:
    - cron: "1 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest GitHub activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: hernieDev/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.mkey }}
